version: '3.8'

services:
  futures-analysis:
    build: .
    container_name: futures-analysis
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    networks:
      - futures-network

  # Redis缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: futures-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - futures-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: futures-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - futures-analysis
    restart: unless-stopped
    networks:
      - futures-network

volumes:
  redis_data:
    driver: local

networks:
  futures-network:
    driver: bridge 